### ISSUE TITLE
Are the States in the Model States Folder Pretrained Models? Model States文件夹里面的是提供的pretrain model吗? 

### ISSUE THREAD

**Issue by kfzyqin** [zsyOAOA/DANet#2]
Hi, 

Thank you very much for producing such great work.

Are the states in the model_states folder pre-trained models? Can we just use those models to re-produce the performance reported in the paper? 

If not, can the authors please provide us with their pre-trained models? 

Thank you very much!

**Comment by zsyOAOA** [comment]
Yes, you can use these models to re-produce the performance reported in the paper.

**Comment by howardgriffin** [comment]
Hi, 
I test the psnr of sidd validation dataset(1280 images) by using the model you provided, but I got psnr 38.5(DANet) and 38.6(DANet+), which is different from the result in your paper. What's wrong did I make?  By the way, I use 'skimage.measure.simple_metrics.compare_psnr' to test psnr.  Or can you provide your computing psnr code? 
Thank you in advance.

**Comment by zsyOAOA** [comment]
I have uploaded the testing code on SIDD validation data set, please refer to test_denoising_SIDD_val.py.

**Comment by howardgriffin** [comment]
> I have uploaded the testing code on SIDD validation data set, please refer to test_denoising_SIDD_val.py.

I have make a mistake before. I read the SIDD dataset by using opencv, which is 'BGR' but not 'RGB'. Thank you again!
