### ISSUE TITLE
Questions about PGAP

### ISSUE THREAD

**Issue by kfzyqin** [zsyOAOA/DANet#3]
Hi, 

Can you please kindly tell us what is the model used for evaluating PGap? Is it just DANet? 

If so, can you please kindly share us with your trained model on the generated noisy dataset? 

If not, can you please tell us what is the denoising model used for evaluating PGap, can also please share us with the trained model? 

Thank you very much!

**Comment by zsyOAOA** [comment]
Please see the demo test_generation_SIDD.py. The trained model on the generated noisy dataset is shared in the folder model_states.
