### ISSUE TITLE
Log Files from Training

### ISSUE THREAD

**Issue by gauenk** [zsyOAOA/DANet#8]
Thank you for your awesome code!

I am hoping you might open-source the log files you have from training. Maybe the training and validation loss as a function of epoch
(and/or batch) with an estimate of the runtime?

**Comment by zsyOAOA** [comment]
Very sorry. The log files have been lost because it has been a long time.

**Comment by gauenk** [comment]
I appreciate your speedy reply. Thank you for sharing!
